import React, { Component, PropTypes } from 'react';
import 'react-select/dist/react-select.css';

var Select = require('react-select');


export default class DiseaseSelection extends Component {
	static propTypes = {
		diseases: PropTypes.array,
		setDisease: PropTypes.func
	}
	render() {
		return (
			<div className='disease-selection'>
				<h2>Let us help you become an EXPERT IN YOU again.</h2>
				<div>I was diagnosed with <DiseaseSelect setDisease={this.props.setDisease} diseases={this.props.diseases} /></div>
			</div>
		);
	}
}
var diseaseLocal = [
   "Adrenal neuroblastoma",
   "Adrenal pheochromocytoma",
   "Anus adenosquamous carcinoma",
   "Anus basaloid carcinoma",
   "Anus melanoma",
   "Anus squamous cell carcinoma",
   "Appendix adenocarcinoma",
   "Appendix goblet cell carcinoid (GCC)",
   "Appendix mucinous neoplasm (NOS)",
   "B-cell prolymphocytic leukemia",
   "Bile duct adenocarcinoma",
   "Bladder GIST",
   "Bladder adenocarcinoma",
   "Bladder carcinoma (NOS)",
   "Bladder leiomyosarcoma",
   "Bladder neuroendocrine carcinoma",
   "Bladder sarcoma",
   "Bladder small cell carcinoma",
   "Bladder squamous cell carcinoma",
   "Bladder squamous cell carcinoma (SCC)",
   "Bladder urothelial (transitional cell) carcinoma",
   "Blood hematologic disorder (NOS)",
   "Blood paroxysmal nocturnal hemoglobinuria (PNH)",
   "Blood sezary syndrome",
   "Bone Chordoma",
   "Bone Ewing sarcoma",
   "Bone adamantinoma",
   "Bone chondroblastoma",
   "Bone chondrosarcoma",
   "Bone chordoma",
   "Bone giant cell lesion (NOS)",
   "Bone giant cell tumor",
   "Bone marrow aplastic anemia",
   "Bone marrow blastic plasmacytoid dendritic cell tumor",
   "Bone marrow hematologic disorder (NOS)",
   "Bone marrow hepatosplenic T-cell lymphoma",
   "Bone marrow leukemia B cell acute (B-ALL)",
   "Bone marrow leukemia T cell acute (T-ALL)",
   "Bone marrow leukemia T cell large granular (T-LGL)",
   "Bone marrow leukemia acute",
   "Bone marrow leukemia hairy cell",
   "Bone marrow leukemia lymphocytic (NOS)",
   "Bone marrow leukemia lymphocytic acute (ALL)",
   "Bone marrow leukemia lymphocytic chronic (CLL)",
   "Bone marrow leukemia mixed lineage (MLL)",
   "Bone marrow leukemia non-lymphocytic (NOS)",
   "Bone marrow leukemia non-lymphocytic acute myelocytic (AML)",
   "Bone marrow leukemia non-lymphocytic acute promyelocytic (APL)",
   "Bone marrow leukemia non-lymphocytic chronic myelocytic (CML)",
   "Bone marrow leukemia non-lymphocytic myelomonocytic (MML)",
   "Bone marrow leukemia pre-lymphocytic acute (pre-ALL)",
   "Bone marrow leukemia-lymphoma T-cell (NOS)",
   "Bone marrow lymph proliferative disease (NOS)",
   "Bone marrow lymphoma Hodgkins disease",
   "Bone marrow lymphoma T-cell (NOS)",
   "Bone marrow lymphoma diffuse large B cell",
   "Bone marrow lymphoma follicular lymphoma",
   "Bone marrow lymphoproliferative disease (NOS)",
   "Bone marrow mastocytosis",
   "Bone marrow multiple myeloma",
   "Bone marrow myelodysplastic syndrome (MDS)",
   "Bone marrow myelodysplastic syndrome (MDS) ",
   "Bone marrow myeloproliferative disorder (MPD)",
   "Bone marrow myeloproliferative neoplasm (MPN)",
   "Bone marrow plasma cell Dyscrasia",
   "Bone marrow plasmacytoma",
   "Bone odontogenic carcinoma",
   "Bone osteoblastoma",
   "Bone osteosarcoma",
   "Bone sarcoma (NOS)",
   "Brain anaplastic astrocytoma",
   "Brain anaplastic meningioma",
   "Brain astrocytoma",
   "Brain astrocytoma pilocytic",
   "Brain astrocytoma pilocytic ",
   "Brain astrocytoma pilomyxoid",
   "Brain atypical teratoid rhabdoid tumor (ATRT)",
   "Brain choroid plexus tumor",
   "Brain craniopharyngioma",
   "Brain dysembryonic neuroepithlial tumor (DNET)",
   "Brain embryonal tumor",
   "Brain ependymoma",
   "Brain gangliocytoma",
   "Brain ganglioglioma",
   "Brain germ cell tumor",
   "Brain glioblastoma",
   "Brain glioblastoma (GBM)",
   "Brain glioma (NOS)",
   "Brain gliosarcoma",
   "Brain gliosis",
   "Brain hemangioblastoma",
   "Brain hemangiopericytoma",
   "Brain malignant ependymoma",
   "Brain medulloblastoma",
   "Brain melanocytoma",
   "Brain meningeal sarcoma",
   "Brain meningioma",
   "Brain neurocytoma",
   "Brain oligoastrocytoma",
   "Brain oligodendroglioma",
   "Brain pineal parenchymal tumor of intermediate differentiation (PPTID)",
   "Brain pineoblastoma",
   "Brain pleomorphic xanthoastrocytoma",
   "Brain pleomorphic xanthroastrocytoma",
   "Brain primitive neuroectoderm tumor (PNET)",
   "Brain subependymoma",
   "Breast",
   "Breast adenoid cystic carcinoma",
   "Breast angiosarcoma",
   "Breast cancer (NOS)",
   "Breast carcinoma  (NOS)",
   "Breast carcinoma (NOS)",
   "Breast carcinoma (NOS) ER negative",
   "Breast carcinoma (NOS) ER positive",
   "Breast carcinoma (NOS) ER unknown",
   "Breast carcinoma (TNBC)",
   "Breast carcinosarcoma",
   "Breast ductal carcinoma in situ",
   "Breast ductal carcinoma in situ (DCIS)",
   "Breast inflammatory carcinoma",
   "Breast invasive ductal carcinoma (IDC)",
   "Breast invasive ductal carcinoma (IDC) ER negative",
   "Breast invasive ductal carcinoma (IDC) ER positive",
   "Breast invasive ductal carcinoma (IDC) ER unknown",
   "Breast invasive lobular carcinoma (ILC)",
   "Breast lobular carcinoma in situ",
   "Breast metaplastic carcinoma",
   "Breast metaplastic carcinoma ",
   "Breast mucinous carcinoma",
   "Breast myoepithelial carcinoma",
   "Breast neuroendocrine carcinoma",
   "Breast papillary carcinoma",
   "Breast papillary carcinoma ",
   "Breast phyllodes tumor",
   "Breast sarcoma",
   "Cervix Neuroendocrine carcinoma",
   "Cervix Small Cell carcinoma",
   "Cervix adenocarcinoma",
   "Cervix adenosquamous carcinoma",
   "Cervix clear cell adenocarcinoma",
   "Cervix neuroendocrine carcinoma",
   "Cervix small cell carcinoma",
   "Cervix squamous cell carcinoma",
   "Cervix squamous cell carcinoma (SCC)",
   "Cervix undifferentiated carcinoma",
   "Chronic myelogenous leukemia in blast crisis",
   "Chronic neutrophilic leukemia",
   "Colon",
   "Colon GIST",
   "Colon adenocarcinoma",
   "Colon adenocarcinoma (CRC)",
   "Colon cancer (NOS)",
   "Colon carcinoid tumor",
   "Colon dysplasia",
   "Colon glomus tumor",
   "Colon neuroendocrine carcinoma",
   "Colorectal",
   "Control",
   "Cowper's gland adenoid cystic carcinoma",
   "Dual breast invasive ductal carcinoma (IDC) and ovary serous carcinoma",
   "Dual leukemia lymphocytic chronic (CLL) and mesothelioma",
   "Duodenum adenocarcinoma",
   "Duodenum adenosquamous carcinoma",
   "Duodenum neuroendocrine tumor",
   "Esophageal/Gastric",
   "Esophagus adenocarcinoma",
   "Esophagus carcinoma (NOS)",
   "Esophagus histiocytic sarcoma",
   "Esophagus neuroendocrine carcinoma",
   "Esophagus squamous cell carcinoma",
   "Esophagus squamous cell carcinoma (SCC)",
   "Esophagus squamous cell carcinoma (SCC) in situ",
   "Extranodal NK/T-cell lymphoma",
   "Eye intraocular melanoma",
   "Eye intraocular squamous cell carcinoma",
   "Eye intraocular squamous cell carcinoma (SCC)",
   "Eye lacrimal duct carcinoma",
   "Fallopian tube adenocarcinoma",
   "Fallopian tube lymphangioleiomyomatosis (LAM)",
   "Fallopian tube serous carcinoma",
   "Gallbladder adenocarcinoma",
   "Gallbladder adenosquamous carcinoma",
   "Gallbladder carcinoma",
   "Gallbladder glomus tumor",
   "Gallbladder squamous cell carcinoma",
   "Gallbladder squamous cell carcinoma (SCC)",
   "Gastric",
   "Gastroesophageal junction adenocarcinoma",
   "Gastrointestinal stromal tumor",
   "Head & Neck",
   "Head and Neck Squamous Cell Carcinoma (HNSCC)",
   "Head and Neck polymorphous adenocarcinoma low grade",
   "Head and neck Schneidarian carcinoma",
   "Head and neck adenocarcinoma",
   "Head and neck adenoid cystic carcinoma",
   "Head and neck ameloblastoma",
   "Head and neck carcinoma (NOS)",
   "Head and neck esthesioneuroblastoma",
   "Head and neck lymphoepithelioma",
   "Head and neck melanoma",
   "Head and neck mucoepidermoid carcinoma",
   "Head and neck myoepithelial carcinoma",
   "Head and neck neuroendocrine carcinoma",
   "Head and neck odontogenic carcinoma",
   "Head and neck spindle cell carcinoma",
   "Head and neck squamous cell carcinoma (HNSCC)",
   "Head and neck squamous papilloma",
   "Heart myxoma",
   "Heart sarcoma",
   "Heart sarcoma (NOS)",
   "Histiocytic sarcoma",
   "Kidney",
   "Kidney Wilms tumor",
   "Kidney cancer (NOS)",
   "Kidney carcinoma (NOS)",
   "Kidney chromophobe carcinoma",
   "Kidney clear cell carcinoma",
   "Kidney collecting duct carcinoma",
   "Kidney malignant rhabdoid tumor (MRT)",
   "Kidney medullary carcinoma",
   "Kidney renal cell carcinoma (NOS)",
   "Kidney renal papillary carcinoma",
   "Kidney rhabdomyosarcoma",
   "Kidney sarcoma (NOS)",
   "Kidney sarcomatoid carcinoma",
   "Kidney urothelial carcinoma",
   "LIVER",
   "Leukemia acute myeloid myelodisplastic syndrome",
   "Leukemia lymphocytic (NOS)",
   "Leukemia lymphocytic acute (ALL)",
   "Leukemia lymphocytic chronic (CLL)",
   "Leukemia mixed lineage (MLL)",
   "Leukemia non-lymphocytic (NOS)",
   "Leukemia non-lymphocytic acute myelocytic (AML)",
   "Leukemia non-lymphocytic acute promyelocytic (APL)",
   "Leukemia non-lymphocytic chronic myelocytic (CML)",
   "Leukemia pre-lymphocytic acute (pre-ALL)",
   "Liver Hepatoblastoma",
   "Liver angiosarcoma",
   "Liver cancer (NOS)",
   "Liver cholangiocarcinoma",
   "Liver hemangioendothelioma",
   "Liver hepatoblastoma",
   "Liver hepatocellular carcinoma (FLO)",
   "Liver hepatocellular carcinoma (HCC)",
   "Liver mixed hepatocellular cholangiocarcinoma",
   "Lung",
   "Lung adenocarcinoma",
   "Lung adenocarcinoma ",
   "Lung adenoid cystic carcinoma",
   "Lung adenosquamous carcinoma",
   "Lung atypical carcinoid",
   "Lung cancer (NOS)",
   "Lung carcinosarcoma",
   "Lung in situ adenocarcinoma",
   "Lung large cell carcinoma",
   "Lung large cell neuroendocrine carcinoma",
   "Lung lymphoepithelioma",
   "Lung lymphoepithelioma ",
   "Lung mucoepidermoid carcinoma",
   "Lung non-small cell carcinoma (NOS)",
   "Lung non-small cell carcinoma (NOS) ",
   "Lung non-small cell carcinoma NOS",
   "Lung non-small cell lung carcinoma",
   "Lung non-small cell lung carcinoma (NOS)",
   "Lung non-small cell lung carcinoma NOS",
   "Lung pleomorphic adenoma",
   "Lung primary adenocarcinoma",
   "Lung pulmonary blastoma",
   "Lung sarcoma",
   "Lung sarcomatoid carcinoma",
   "Lung sclerosing hemangioma",
   "Lung small cell undifferentiated carcinoma",
   "Lung solitary fibrous tumor",
   "Lung squamous cell carcinoma",
   "Lung squamous cell carcinoma (SCC)",
   "Lung typical carcinoid",
   "Lung, non small cell lung carcinoma",
   "Lymph node Castleman's disease",
   "Lymph node NK T-cell lymphoma (NOS)",
   "Lymph node anaplastic large cell lymphoma",
   "Lymph node histiocytosis Rosai-Dorfman",
   "Lymph node leukemia lymphocytic (NOS)",
   "Lymph node leukemia lymphocytic acute (ALL)",
   "Lymph node leukemia lymphocytic chronic (CLL)",
   "Lymph node leukemia lymphocytic chronic (CLL) ",
   "Lymph node leukemia non-lymphocytic acute myelocytic (AML)",
   "Lymph node leukemia non-lymphocytic acute myelocytic (AML) ",
   "Lymph node leukemia non-lymphocytic chronic myelocytic (CML)",
   "Lymph node lymphoma B-cell (NOS)",
   "Lymph node lymphoma Burkitt",
   "Lymph node lymphoma Hodgkins disease",
   "Lymph node lymphoma T-cell (NOS)",
   "Lymph node lymphoma angioimmunoblastic T-cell (AILT)",
   "Lymph node lymphoma angioimmunoblastic T-cell (AITL)",
   "Lymph node lymphoma diffuse large B cell",
   "Lymph node lymphoma follicular lymphoma",
   "Lymph node lymphoma lymphoblastic",
   "Lymph node lymphoma mantle cell",
   "Lymph node lymphoma marginal zone",
   "Lymph node lymphoma mediastinal B-cell (PMBCL)",
   "Lymph node lymphoma mediastinal B-cell(PMBCL)",
   "Lymph node lymphoma non-Hodgkins (NOS)",
   "Lymph node lymphoma plasmablastic",
   "Lymphoma",
   "Lymphoma Burkitt‚Äôs",
   "Lymphoma Hodgkins disease",
   "Lymphoma Waldenstroms",
   "Lymphoma diffuse large B cell",
   "Lymphoma follicular lymphoma",
   "Lymphoma lymphoblastic",
   "Lymphoma mantle cell",
   "Lymphoma non-Hodgkins (NOS)",
   "Lymphoma, B-cell",
   "Lymphoma, T cell",
   "MDS-MPN",
   "Mediastinum germ cell tumor",
   "Melanoma",
   "Monoclonal gammopathy of undetermined significance (MGUS)",
   "Multiple Myeloma",
   "Myelodysplastic-Myeloproliferative neoplasm (MDS-MPN)",
   "Myelodysplastic-myeloproliferative neoplasm (MDS-MPN)",
   "Myeloid sarcoma",
   "NK T-cell neoplasm",
   "NORMAL",
   "NSCLC",
   "Nasopharynx and paranasal sinuses adenocarcinoma",
   "Nasopharynx and paranasal sinuses esthesioneuroblastoma",
   "Nasopharynx and paranasal sinuses lymphoepithelioma",
   "Nasopharynx and paranasal sinuses squamous cell carcinoma",
   "Nasopharynx and paranasal sinuses teratocarcinosarcoma",
   "Nasopharynx and paranasal sinuses undifferentiated carcinoma",
   "New DO Required",
   "Normal",
   "Normal F1",
   "Normal Heme",
   "Other",
   "Ovarian",
   "Ovarian endometrioid adenocarcinoma",
   "Ovarian epithelial carcinoma",
   "Ovary Malignant struma ovarii",
   "Ovary Malignant struma ovarii ",
   "Ovary Sertoli-Leydig cell tumor",
   "Ovary cancer (NOS)",
   "Ovary carcinoid tumor",
   "Ovary carcinoma mixed histology",
   "Ovary carcinosarcoma",
   "Ovary clear cell carcinoma",
   "Ovary endometrioid adenocarcinoma",
   "Ovary endometrioid tumor (EBT/APET)",
   "Ovary epithelial carcinoma (NOS)",
   "Ovary female adnexal tumor of Wolfian origin",
   "Ovary germ cell tumor",
   "Ovary granulosa cell tumor",
   "Ovary high grade serous carcinoma",
   "Ovary low grade serous carcinoma",
   "Ovary low grade serous carcinoma ",
   "Ovary malignant mixed mesodermal tumor (MMMT)",
   "Ovary malignant struma ovarii",
   "Ovary mucinous carcinoma",
   "Ovary mucinous tumor(LMP)",
   "Ovary neuroendocrine carcinoma",
   "Ovary sarcoma (NOS)",
   "Ovary serous carcinoma",
   "Ovary serous tumor (LMP)",
   "Ovary serous tumor(LMP)",
   "Ovary sex cord tumor with annular tubules (SCTAT)",
   "Ovary sex-cord stromal tumor",
   "Ovary small cell carcinoma",
   "",
   "Pancreas Invasive intraductal papillary mucinous tumor (IPMT)",
   "Pancreas Neuroendocrine carcinoma",
   "Pancreas acinar cell carcinoma",
   "Pancreas cancer (NOS)",
   "Pancreas carcinoma (NOS)",
   "Pancreas carcinoma (NOS) ",
   "Pancreas ductal adenocarcinoma",
   "Pancreas ductal adenocarcinoma ",
   "Pancreas ductal carcinoma",
   "Pancreas hepatoid carcinoma",
   "Pancreas intraductal papillary mucinous tumor (IPMT)",
   "Pancreas islet cell tumor",
   "Pancreas mucinous cystadenocarcinoma",
   "Pancreas neuroendocrine carcinoma",
   "Pancreas neuroendocrine tumor (pNET)",
   "Pancreas pancreatoblastoma",
   "Pancreas solid and papillary tumor",
   "Pancreas solid pseudopapillary tumor",
   "Pancreatic",
   "Pancreatobiliary carcinoma (NOS)",
   "Parathyroid carcinoma",
   "Penis squamous cell carcinoma",
   "Penis squamous cell carcinoma (SCC)",
   "Penis urothelial carcinoma",
   "Pericardium mesothelioma",
   "Peritoneum adenocarcinoma",
   "Peritoneum clear cell carcinoma",
   "Peritoneum endometrioid adenocarcinoma",
   "Peritoneum mesothelioma",
   "Peritoneum mucinous carcinoma",
   "Peritoneum serous carcinoma",
   "Peritoneum serous tumor (LMP)",
   "Pineal parenchymal tumor",
   "Pituitary adenoma",
   "Pituitary carcinoma",
   "Placenta choriocarcinoma",
   "Placenta trophoblastic tumor",
   "Pleura mesothelioma",
   "Prostate acinar adenocarcinoma",
   "Prostate adenoid cystic carcinoma",
   "Prostate cancer (NOS)",
   "Prostate carcinoma",
   "Prostate carcinosarcoma",
   "Prostate ductal adenocarcinoma",
   "Prostate neuroendocrine carcinoma",
   "Prostate sarcoma (NOS)",
   "Prostate undifferentiated carcinoma",
   "Rectum adenocarcinoma (CRC)",
   "Rectum carcinoid tumor",
   "Rectum myoepithelial carcinoma",
   "Rectum neuroendocrine carcinoma",
   "Rectum squamous cell carcinoma",
   "Rectum squamous cell carcinoma (SCC)",
   "Rectum squamous cell carcinoma (SCC) ",
   "Salivary Gland Carcinoma",
   "Salivary gland MASC",
   "Salivary gland acinic cell tumor",
   "Salivary gland adenocarcinoma",
   "Salivary gland adenoid cystic carcinoma",
   "Salivary gland carcinoma (NOS)",
   "Salivary gland carcinoma ex pleomorphic adenoma",
   "Salivary gland clear cell carcinoma",
   "Salivary gland duct carcinoma",
   "Salivary gland mucoepidermoid carcinoma",
   "Salivary gland myoepithelial carcinoma",
   "Salivary gland polymorphous low grade adenocarcinoma (PLGA)",
   "Salivary gland sarcoma (NOS)",
   "Salivary gland undifferentiated carcinoma",
   "Sarcomatoid carcinoma",
   "Scrotum squamous cell carcinoma (SCC)",
   "Skin Kaposi sarcoma",
   "Skin Merkel cell carcinoma",
   "Skin adnexal carcinoma",
   "Skin appendage tumor (NOS)",
   "Skin atypical fibroxanthoma",
   "Skin basal cell carcinoma",
   "Skin dermatofibrosarcoma",
   "Skin desmoplastic melanoma",
   "Skin extramammary Pagets disease",
   "Skin glomus tumor",
   "Skin lymphoma (NOS)",
   "Skin lymphoma T-cell",
   "Skin melanocyte dysplasia",
   "Skin melanoma",
   "Skin mycosis fungoides",
   "Skin sarcoma (NOS)",
   "Skin squamous cell carcinoma",
   "Skin squamous cell carcinoma (SCC)",
   "Small intestine GIST",
   "Small intestine adenocarcinoma",
   "Small intestine carcinoid",
   "Small intestine gastrointestinal neuroectodermal tumor",
   "Small intestine leiomyosarcoma",
   "Small intestine neuroendocrine carcinoma",
   "Soft tissue Ewing sarcoma",
   "Soft tissue Follicular dendritic cell sarcoma",
   "Soft tissue NUT midline carcinoma",
   "Soft tissue alveolar soft part sarcoma",
   "Soft tissue angiomyolipoma",
   "Soft tissue angiosarcoma",
   "Soft tissue arteriovenous malformation",
   "Soft tissue chondrosarcoma",
   "Soft tissue clear cell sarcoma",
   "Soft tissue desmoplastic small round cell tumor",
   "Soft tissue embryonal rhabdomyosarcoma",
   "Soft tissue ependymoma",
   "Soft tissue epithelioid sarcoma",
   "Soft tissue eplithelioid sarcoma",
   "Soft tissue extrarenal rhabdoid tumor",
   "Soft tissue fibromatosis",
   "Soft tissue fibrosarcoma",
   "Soft tissue follicular dendrite cell sarcoma",
   "Soft tissue follicular dendritic cell sarcoma",
   "Soft tissue ganglioneuroma",
   "Soft tissue granular cell tumor",
   "Soft tissue granulocytic sarcoma",
   "Soft tissue hamartoma",
   "Soft tissue hemangioendothelioma",
   "Soft tissue hemangioma",
   "Soft tissue hemangiopericytoma",
   "Soft tissue histiocytic or dendritic cell neoplasm",
   "Soft tissue histiocytoma Langerans",
   "Soft tissue histiocytoma Langerhans",
   "Soft tissue histiocytoma juvenile xanthogranuloma",
   "Soft tissue histiocytoma non-Langerans (ECD)",
   "Soft tissue histiocytosis (NOS)",
   "Soft tissue histiocytosis Langerhans",
   "Soft tissue histiocytosis Rosai-Dorfman",
   "Soft tissue histiocytosis juvenile xanthogranuloma",
   "Soft tissue histiocytosis non-Langerhans (ECD)",
   "Soft tissue inflammatory myofibroblastic tumor",
   "Soft tissue leiomyomatosis",
   "Soft tissue leiomyosarcoma",
   "Soft tissue lipoma and angiolipoma",
   "Soft tissue liposarcoma",
   "Soft tissue lymphangioma",
   "Soft tissue malignant fibrous histiocytoma (MFH)",
   "Soft tissue malignant granular cell tumor",
   "Soft tissue malignant peripheral nerve sheath tumor (MPNST)",
   "Soft tissue melanocytic lesion",
   "Soft tissue myoepithelial carcinoma",
   "Soft tissue myoepithelioma",
   "Soft tissue myxofibrosarcoma",
   "Soft tissue neuroblastoma",
   "Soft tissue neurofibroma",
   "Soft tissue ossifying fibromyxoid tumor",
   "Soft tissue paraganglioma",
   "Soft tissue perivascular epithelioid cell tumor (PEComa)",
   "Soft tissue pigmented villonodular synovitis",
   "Soft tissue pleomorphic rhabdomyosarcoma",
   "Soft tissue primitive neuroectoderm tumor (PNET)",
   "Soft tissue rhabdomyosarcoma",
   "Soft tissue rhabdomyosarcoma (NOS)",
   "Soft tissue rhabdomyosarcoma alveolar",
   "Soft tissue rhabdomyosarcoma botryoid",
   "Soft tissue rhabdomyosarcoma embryonal",
   "Soft tissue rhabdomyosarcoma pleomorphic",
   "Soft tissue rhabdomyosarcoma pleomorphic ",
   "Soft tissue rhabdomyosarcoma, alveolar",
   "Soft tissue rhabdomyosarcoma, embryonal",
   "Soft tissue rhabdomyosarcoma, pleomorphic",
   "Soft tissue round cell tumor (NOS)",
   "Soft tissue sarcoma (NOS)",
   "Soft tissue sarcoma undifferentiated",
   "Soft tissue schwannoma",
   "Soft tissue small cell neuroendocrine carcinoma",
   "Soft tissue solitary fibrous tumor",
   "Soft tissue synovial sarcoma",
   "Soft tissue teratoma",
   "Soft tissue tumor with myopericytic differentiation",
   "Soft tissue, proliferative disorder NOS",
   "Spine astrocytoma",
   "Spine ependymoma",
   "Spine glioma (NOS)",
   "Spleen angiosarcoma",
   "Spleen sarcoma",
   "Spleen sarcoma (NOS)",
   "Stomach GIST",
   "Stomach Kaposi sarcoma",
   "Stomach adenocarcinoma (NOS)",
   "Stomach adenocarcinoma NOS",
   "Stomach adenocarcinoma diffuse type",
   "Stomach adenocarcinoma intestinal type",
   "Stomach adenocarcinoma, diffuse type",
   "Stomach adenocarcinoma, intestinal type",
   "Stomach leiomyosarcoma",
   "Stomach neuroendocrine carcinoma",
   "T-prolymphocytic leukemia",
   "Testis Leydig cell tumor",
   "Testis Sertoli cell tumor",
   "Testis embryonal rhabdomyosarcoma",
   "Testis germ cell tumor (mixed)",
   "Testis germ cell tumor (non-seminoma)",
   "Testis germ cell tumor (seminoma)",
   "Testis mesothelioma",
   "Testis paratesticular serous carcinoma",
   "Testis sex cord stromal tumor",
   "Thymoma",
   "Thymus atypical carcinoid",
   "Thymus carcinoma",
   "Thymus carcinoma (NOS)",
   "Thymus histiocytoma Langerhans",
   "Thymus neuroendocrine carcinoma",
   "Thymus thymoma (NOS)",
   "Thymus thymoma lymphocytic",
   "Thymus thymoma mixed",
   "Thyroid CASTLE carcinoma",
   "Thyroid anaplastic carcinoma",
   "Thyroid carcinoma (NOS)",
   "Thyroid carcinoma, type Unspecified",
   "Thyroid follicular carcinoma",
   "Thyroid follicular oncocytic carcinoma",
   "Thyroid medullary carcinoma",
   "Thyroid papillary carcinoma",
   "Thyroid papillary carcinoma ",
   "Trachea adenoid cystic carcinoma",
   "Trachea squamous cell carcinoma (SCC)",
   "Tumor",
   "UNKNOWN",
   "Unknown",
   "Unknown F1",
   "Unknown F1H",
   "Unknown Primary Adenocarcinoma",
   "Unknown primary F1H malignant neoplasm (NOS)",
   "Unknown primary GIST",
   "Unknown primary Leiomyosarcoma",
   "Unknown primary adenocarcinoma",
   "Unknown primary adenoid cystic carcinoma",
   "Unknown primary adenosarcoma",
   "Unknown primary cancer (NOS)",
   "Unknown primary carcinoid",
   "Unknown primary carcinoma",
   "Unknown primary carcinoma (NOS)",
   "Unknown primary carcinosarcoma",
   "Unknown primary gastrointestinal stromal tumor (GIST)",
   "Unknown primary germ cell tumor",
   "Unknown primary leiomyosarcoma",
   "Unknown primary malignant neoplasm",
   "Unknown primary malignant neoplasm (NOS)",
   "Unknown primary melanoma",
   "Unknown primary mucoepidermoid carcinoma",
   "Unknown primary myoepithelial carcinoma",
   "Unknown primary sarcoma (NOS)",
   "Unknown primary sarcomatoid carcinoma",
   "Unknown primary serous carcinoma",
   "Unknown primary squamous cell carcinoma (SCC)",
   "Unknown primary squamous cell carcinoma (SCC) ",
   "Unknown primary undifferentiated large cell carcinoma",
   "Unknown primary undifferentiated large cell carcinoma ",
   "Unknown primary undifferentiated neuroendocrine carcinoma",
   "Unknown primary undifferentiated small cell carcinoma",
   "Unknown primary undifferentiated small cell carcinoma ",
   "Unknown primary urothelial carcinoma",
   "Unknown primary, adenocarcinoma",
   "Unknown primary, adenocarinoma",
   "Unknown primary, adenoid cystic carcinoma",
   "Unknown primary, carcinoma (NOS)",
   "Unknown primary, melanoma",
   "Unknown primary, sarcoma",
   "Unknown primary, squamous cell carcinoma",
   "Unknown primary, undifferentiated large cell carcinoma",
   "Unknown primary, undifferentiated neuroendocrine carcinoma",
   "Unknown primary, undifferentiated small cell carcinoma",
   "Urachus carcinoma (NOS)",
   "Ureter adenocarcinoma",
   "Ureter urothelial carcinoma",
   "Ureter urothelial carcinoma in situ",
   "Urethra adenocarcinoma",
   "Urethra clear cell carcinoma",
   "Urethra squamous cell carcinoma",
   "Urethra squamous cell carcinoma (SCC)",
   "Urethra urothelial carcinoma",
   "Urinary Bladder",
   "Uterus adenosarcoma",
   "Uterus carcinosarcoma",
   "Uterus endometrial adenocarcinoma (NOS)",
   "Uterus endometrial adenocarcinoma clear cell",
   "Uterus endometrial adenocarcinoma endometrioid",
   "Uterus endometrial adenocarcinoma papillary serous",
   "Uterus endometrial small cell carcinoma",
   "Uterus endometrial stromal sarcoma",
   "Uterus endometrium atypical polypoid adenomyoma (APA)",
   "Uterus endometrium hyperplasia",
   "Uterus gestational trophoblastic tumor epitheloid",
   "Uterus leiomyosarcoma",
   "Uterus malignant mixed mesodermal tumor (MMMT)",
   "Uterus neuroendocrine carcinoma",
   "Uterus perivascular epithelioid cell tumor (PEComa)",
   "Uterus sarcoma (NOS)",
   "Uterus smooth muscle tumor of uncertain malignant potential (STUMP)",
   "Vagina Melanoma",
   "Vagina adenocarcinoma",
   "Vagina neuroendocrine carcinoma",
   "Vagina squamous cell carcinoma",
   "Vagina squamous cell carcinoma (SCC)",
   "Vulva adenocarcinoma",
   "Vulva adenoid cystic carcinoma",
   "Vulva melanoma",
   "Vulva squamous cell carcinoma",
   "Vulva squamous cell carcinoma (SCC)"
];

class DiseaseSelect extends Component {
	static propTypes = {
		diseases: PropTypes.array,
		setDisease: PropTypes.func
	};
	render() {
		let selectOnChange = (val) => {
			this.props.setDisease(val);
		}

		let getSelectionList = (diseases) => {
			let diseaseArray = [];
			diseases.forEach(function (disease){
				diseaseArray.push({value : disease, label : disease});
			});
			return diseaseArray;
		}

		return (
			<Select
				name="DiseaseSelect-Form-Field"
				value="Lung non-small cell carcinoma (NOS)"
				onChange={selectOnChange}
				options={getSelectionList(diseaseLocal)}
				/>

		);
	}
}
